DROP TABLE IF EXISTS `USER_PROJECT`;

CREATE TABLE `USER_PROJECT`
(
    `USER_ID`    BIGINT    NOT NULL,
    `PROJECT_ID` BIGINT    NOT NULL,
    `CREATED_AT` timestamp NOT NULL,
    `UPDATED_AT` timestamp NOT NULL,
    CONSTRAINT `PK_USER_PROJECT` PRIMARY KEY (`USER_ID`, `PROJECT_ID`),
    CONSTRAINT `FK_USER_PROJECT_USER_ID`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`) ON DELETE NO ACTION,
    CONSTRAINT `FK_USER_PROJECT_PROJECT_ID`
        FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`) ON DELETE NO ACTION
);
