ALTER TABLE `REQUIREMENT_UNIT_PROCESS`
    ADD COLUMN `REQUIREMENT_UNIT_PROCESS_ID` BIGINT FIRST;

SET @row_number = 0;
UPDATE REQUIREMENT_UNIT_PROCESS
SET REQUIREMENT_UNIT_PROCESS_ID = CONCAT(
        DATE_FORMAT(NOW(), '%Y%m%d%H%i%s'),
        LPAD((@row_number := @row_number + 1), 5, '0')
                                  );

ALTER TABLE REQUIREMENT_UNIT_PROCESS
    MODIFY COLUMN REQUIREMENT_UNIT_PROCESS_ID BIGINT NOT NULL;

ALTER TABLE REQUIREMENT_UNIT_PROCESS
    ADD PRIMARY KEY (REQUIREMENT_UNIT_PROCESS_ID);