DROP TABLE IF EXISTS `REQUIREMENT_CATEGORY`;

CREATE TABLE `REQUIREMENT_CATEGORY`
(
    `REQUIREMENT_CATEGORY_ID`     BIGINT       NOT NULL,
    `PROJECT_ID`                  BIGINT       NOT NULL,
    `VERSION_MAJOR_NUMBER`        INT          NOT NULL,
    `VERSION_MINOR_NUMBER`        INT          NOT NULL,
    `REQUIREMENT_CATEGORY_NAME`   VARCHAR(255) NOT NULL,
    `REQUIREMENT_CATEGORY_PREFIX` VARCHAR(255) NOT NULL,
    `CREATED_AT`                  TIMESTAMP    NOT NULL,
    `UPDATED_AT`                  TIMESTAMP    NOT NULL,

    CONSTRAINT `PK_REQUIREMENT_CATEGORY` PRIMARY KEY (`REQUIREMENT_CATEGORY_ID`),
    CONSTRAINT `FK_REQUIREMENT_CATEGORY_VERSION`
        FOREIGN KEY (`PROJECT_ID`, `VERSION_MAJOR_NUMBER`, `VERSION_MINOR_NUMBER`)
            REFERENCES `VERSION` (`PROJECT_ID`, `VERSION_MAJOR_NUMBER`, `VERSION_MINOR_NUMBER`)
)