DROP TABLE IF EXISTS `VERSION`;

CREATE TABLE `VERSION`
(
    `PROJECT_ID`     BIGINT       NOT NULL,
    `VERSION_NUMBER` VARCHAR(255) NOT NULL,
    `CREATED_AT`     timestamp    NOT NULL,
    CONSTRAINT `PK_VERSION` PRIMARY KEY (`PROJECT_ID`, `VERSION_NUMBER`),
    CONSTRAINT `FK_VERSION_PROJECT_ID`
        FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`) ON DELETE NO ACTION
);
