DROP TABLE IF EXISTS `PROJECT_FACTOR`;

CREATE TABLE `PROJECT_FACTOR`
(
    `PROJECT_FACTOR_ID` BIGINT       NOT NULL,
    `PROJECT_ID`        BIGINT       NOT NULL,
    `UNIT_COST`         INT          NULL,
    `TEAM_SIZE`         INT          NULL,
    `COCOMO_TYPE`       VARCHAR(255) NULL,
    `CREATED_AT`        timestamp    NOT NULL,
    `UPDATED_AT`        timestamp    NOT NULL,
    CONSTRAINT `PK_PROJECT_FACTOR` PRIMARY KEY (`PROJECT_FACTOR_ID`),
    CONSTRAINT `FK_PROJECT_FACTOR_PROJECT_ID`
        FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`) ON DELETE NO ACTION
);
