    DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
                      `USER_ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
                      `EMAIL` VARCHAR(255) NOT NULL UNIQUE,
                      `PASSWORD` VARCHAR(255) NOT NULL,
                      `NAME` VARCHAR(100) NOT NULL,
                      `SOCIAL_ID` VARCHAR(255),
                      `LOGIN_TYPE` VARCHAR(255) NOT NULL,
                      `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);