ALTER TABLE `REQUIREMENT_UNIT_PROCESS`
    DROP FOREIGN KEY `FK_REQUIREMENT_UNIT_PROCESS_REQUIREMENT_ID`,
    DROP FOREIGN KEY `FK_REQUIREMENT_UNIT_PROCESS_UNIT_PROCESS_ID`;

ALTER TABLE `REQUIREMENT_UNIT_PROCESS` DROP PRIMARY KEY;