-- 1) VERSION 테이블의 컬럼명 변경
ALTER TABLE `VERSION`
    RENAME COLUMN `MAJOR_NUMBER` TO `VERSION_MAJOR_NUMBER`,
    RENAME COLUMN `MINOR_NUMBER` TO `VERSION_MINOR_NUMBER`;

-- 2) FILE 테이블의 컬럼명 변경
ALTER TABLE `FILE`
    RENAME COLUMN `MAJOR_NUMBER` TO `VERSION_MAJOR_NUMBER`,
    RENAME COLUMN `MINOR_NUMBER` TO `VERSION_MINOR_NUMBER`;
