DROP TABLE IF EXISTS `INVITATION`;

CREATE TABLE `INVITATION` (
    `INVITATION_TOKEN` CHAR(50)  NOT NULL,
    `PROJECT_ID`       BIGINT    NOT NULL,
    `EXPIRE_DATE`      TIMESTAMP NOT NULL ,
    PRIMARY KEY (`INVITATION_TOKEN`, `PROJECT_ID`)
)