CREATE TABLE `REQUIREMENT_UNIT_PROCESS`
(
    `REQUIREMENT_ID`  BIGINT       NOT NULL,
    `UNIT_PROCESS_ID` BIGINT       NOT NULL,
    `CREATED_AT`      TIMESTAMP    NOT NULL,
    `UPDATED_AT`      TIMESTAMP    NOT NULL,

    PRIMARY KEY (`REQUIREMENT_ID`, `UNIT_PROCESS_ID`),

    CONSTRAINT `FK_REQUIREMENT_UNIT_PROCESS_REQUIREMENT_ID`
        FOREIGN KEY (`REQUIREMENT_ID`) REFERENCES `REQUIREMENT` (`REQUIREMENT_ID`),

    CONSTRAINT `FK_REQUIREMENT_UNIT_PROCESS_UNIT_PROCESS_ID`
        FOREIGN KEY (`UNIT_PROCESS_ID`) REFERENCES `UNIT_PROCESS` (`UNIT_PROCESS_ID`)
)