DROP TABLE IF EXISTS `COCOMO_MULTIPLIER`;

CREATE TABLE `COCOMO_MULTIPLIER` (
    `COCOMO_MULTIPLIER_ID` BIGINT      NOT NULL,
    `PROJECT_ID`           BIGINT      NOT NULL,
    `RCPX`                 VARCHAR(20) NOT NULL,
    `RUSE`                 VARCHAR(20) NOT NULL,
    `PDIF`                 VARCHAR(20) NOT NULL,
    `PERS`                 VARCHAR(20) NOT NULL,
    `SCED`                 VARCHAR(20) NOT NULL,
    `FCIL`                 VARCHAR(20) NOT NULL,
    `CREATED_AT`           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT`           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT `PK_COCOMO_MULTIPLIER` PRIMARY KEY (`COCOMO_MULTIPLIER_ID`),
    CONSTRAINT `FK_COCOMO_MULTIPLIER_PROJECT_ID`
        FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`) ON DELETE NO ACTION
);
