CREATE TABLE `UNIT_PROCESS`
(
    `UNIT_PROCESS_ID`   BIGINT       NOT NULL,
    `UNIT_PROCESS_NAME` VARCHAR(255) NOT NULL,
    `FUNCTION_TYPE`     VARCHAR(255) NOT NULL,
    `CREATED_AT`        TIMESTAMP    NOT NULL,
    `UPDATED_AT`        TIMESTAMP    NOT NULL,

    CONSTRAINT `PK_UNIT_PROCESS` PRIMARY KEY (`UNIT_PROCESS_ID`)
);