ALTER TABLE `USER_PROJECT` RENAME TO `PROJECT_MEMBER`;

ALTER TABLE `PROJECT_MEMBER`
    ADD COLUMN `STATE` VARCHAR(20) NOT NULL AFTER `PROJECT_ID`,
    ADD COLUMN `ROLE`  VARCHAR(20) NOT NULL AFTER `STATE`;