DROP TABLE IF EXISTS `FILE`;

CREATE TABLE `FILE`
(
    `FILE_ID`        BIGINT       NOT NULL,
    `PROJECT_ID`     BIGINT       NOT NULL,
    `VERSION_NUMBER` VARCHAR(255) NOT NULL,
    `TYPE`           VARCHAR(255) NOT NULL,
    `NAME`           VARCHAR(255) NOT NULL,
    `UPLOADER_ID`    BIGINT       NULL,
    `PATH`           VARCHAR(255) NOT NULL,
    `EXTENSION`      VARCHAR(255) NOT NULL,
    `CREATED_AT`     timestamp    NOT NULL,
    `UPDATED_AT`     timestamp    NOT NULL,
    CONSTRAINT `PK_FILE` PRIMARY KEY (`FILE_ID`),
    CONSTRAINT `FK_FILE_PROJECT_ID`
        FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`) ON DELETE NO ACTION,
    CONSTRAINT `FK_FILE_VERSION`
        FOREIGN KEY (`PROJECT_ID`, `VERSION_NUMBER`) REFERENCES `VERSION` (`PROJECT_ID`, `VERSION_NUMBER`) ON DELETE NO ACTION
);
