ALTER TABLE `UNIT_PROCESS`
    ADD COLUMN `PROJECT_ID` BIGINT AFTER `UNIT_PROCESS_ID`;

ALTER TABLE `UNIT_PROCESS`
    ADD COLUMN `VERSION_MAJOR_NUMBER` INT AFTER `PROJECT_ID`;

ALTER TABLE `UNIT_PROCESS`
    ADD COLUMN `VERSION_MINOR_NUMBER` INT AFTER `VERSION_MAJOR_NUMBER`;

UPDATE `UNIT_PROCESS` up
    JOIN (
        SELECT DISTINCT
            rup.`UNIT_PROCESS_ID`,
            r.`PROJECT_ID`,
            r.`VERSION_MAJOR_NUMBER`,
            r.`VERSION_MINOR_NUMBER`
        FROM `REQUIREMENT_UNIT_PROCESS` rup
                 JOIN `REQUIREMENT` r ON rup.`REQUIREMENT_ID` = r.`REQUIREMENT_ID`
    ) req_info ON up.`UNIT_PROCESS_ID` = req_info.`UNIT_PROCESS_ID`
SET
    up.`PROJECT_ID` = req_info.`PROJECT_ID`,
    up.`VERSION_MAJOR_NUMBER` = req_info.`VERSION_MAJOR_NUMBER`,
    up.`VERSION_MINOR_NUMBER` = req_info.`VERSION_MINOR_NUMBER`,
    up.`UPDATED_AT` = NOW();

ALTER TABLE `UNIT_PROCESS`
ADD CONSTRAINT `FK_UNIT_PROCESS_PROJECT_ID`
    FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`);

ALTER TABLE `UNIT_PROCESS`
ADD CONSTRAINT `FK_UNIT_PROCESS_VERSION`
    FOREIGN KEY (`PROJECT_ID`, `VERSION_MAJOR_NUMBER`, `VERSION_MINOR_NUMBER`)
    REFERENCES `VERSION` (`PROJECT_ID`, `VERSION_MAJOR_NUMBER`, `VERSION_MINOR_NUMBER`);
