DROP TABLE IF EXISTS `PROJECT`;

CREATE TABLE `PROJECT`
(
    `PROJECT_ID`  BIGINT       NOT NULL,
    `NAME`        VARCHAR(255) NOT NULL,
    `DESCRIPTION` LONGTEXT     NOT NULL,
    `CREATED_AT`  timestamp    NOT NULL,
    `UPDATED_AT`  timestamp    NOT NULL,
    CONSTRAINT `PK_PROJECT` PRIMARY KEY (`PROJECT_ID`)
);