DROP TABLE IF EXISTS `FP_WEIGHTS`;

CREATE TABLE `FP_WEIGHTS`
(
    `FP_WEIGHTS_ID` BIGINT         NOT NULL,
    `PROJECT_ID`   BIGINT         NOT NULL,
    `ILF_WEIGHT`   DECIMAL(10, 1) NOT NULL,
    `EIF_WEIGHT`   DECIMAL(10, 1) NOT NULL,
    `EI_WEIGHT`    DECIMAL(10, 1) NOT NULL,
    `EO_WEIGHT`    DECIMAL(10, 1) NOT NULL,
    `EQ_WEIGHT`    DECIMAL(10, 1) NOT NULL,
    `CREATED_AT`   TIMESTAMP      NOT NULL,
    `UPDATED_AT`   TIMESTAMP      NOT NULL,
    CONSTRAINT `PK_FP_WEIGHTS` PRIMARY KEY (`FP_WEIGHTS_ID`),
    CONSTRAINT `FK_FP_WEIGHTS_PROJECT_ID`
        FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`) ON DELETE NO ACTION
)