DROP TABLE IF EXISTS `PROJECT_LANGUAGE`;

CREATE TABLE `PROJECT_LANGUAGE`
(
    `PROJECT_LANGUAGE_ID` BIGINT    NOT NULL,
    `PROJECT_ID`          BIGINT    NOT NULL,
    `LANGUAGE`            VARCHAR(255)       NULL,
    `RATE`                INT       NULL,
    `CREATED_AT`          timestamp NOT NULL,
    `UPDATED_AT`          timestamp NOT NULL,
    CONSTRAINT `PK_PROJECT_LANGUAGE` PRIMARY KEY (`PROJECT_LANGUAGE_ID`),
    CONSTRAINT `FK_PROJECT_LANGUAGE_PROJECT_ID`
        FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`) ON DELETE NO ACTION
);
